### ISSUE TITLE
degree centigrade symbol

### ISSUE THREAD

**Issue by spinoinside** [OutsourcedGuru/pizero-oled#2]
hi,
it's possible to display the degree centigrade symbol **°C** instead of **'C** ?
thanks

**Comment by OutsourcedGuru** [comment]
I'm not sure what code was there in the (unincluded) script which displays that information on the screen, to be honest. But it should be possible to do this with whatever script you write.

I'm guessing that the [underlying script](https://github.com/adafruit/Adafruit_Python_SSD1306/blob/master/examples/stats.py) was from Adafruit's repository. Since their version doesn't include the temperature, I'm guessing that I edited their script to add it.

If it displays an apostrophe rather than the degree symbol it possibly needs to adjust the codepage at the top of the Python script for whatever it's supposed to be, like UNICODE.
